---
- name: "extract zipped artifact."
  unarchive:
    src: /root/project/artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz
    dest: /home/ubuntu/

- name: "start app."
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
